### ISSUE TITLE
config file's self directory

### ISSUE THREAD

**Issue by NetLancer** [ForestMist/feri#35]
Can't cope with setting feri-config.js parameter path.source/destination to its root (meaning where config file self is located). Weird thing i've tried out 
'./',  '.',  '/',  '' 
but none worked.

**Comment by NetLancer** [comment]
First, i hate to think that project's heading towards abandonment - too useful a tool )).
Actually feri-config.js lives in between my_defined_src & my_defined_dest. But my_defined_dist is not fully mine (use it inside symphony-2 project) and there are few other files/folders already existing which don't (and can't too) want to wipe out and therefore need ways for more precise definition of what & where to be compiled - most importantly - without touching other possible folders inside dest

**Comment by NetLancer** [comment]
And i wonder if the following config lines are applicable for purposes above:
//     feri.config.glob.watch.source = 'pages/theme/**/*.{css,js}'
//     feri.config.glob.clean = 'assets/*.{css,js}'
//     feri.config.glob.build = 'pages/theme/*.concat' // concat file combines few other assets another level down // the hierarchy - works ok
// To be substitute for either replace following lines:
   feri.config.option.clean      = true
    feri.config.option.build      = true
     feri.config.option.watch      = true
  // paths
     feri.config.path.source = "pages/theme"
     feri.config.path.dest   = "assets"    

Pardon me for dummy questions, i'm not really good at this sort of tools but i believe that's all i'm gonna need to figure out for my basic tasks. Grunt and gulp seems too redundant

**Comment by ForestMist** [comment]
I update Feri every so often (few months) to bring in the latest dependencies. Bug fixes as needed of course.

Long term, I want to rewrite Feri to use Async/Await and remove more dependencies. That is not likely to happen until 2019 or beyond though.

**Comment by ForestMist** [comment]
A core concept of Feri is that the destination (or dest) folder is expected to be completely expendable at all times. Any files that need to get published to dest should live in the source directory. There are Feri options that will completely destroy the dest folder for things like a republish so keeping anything valuable in the dest folder is dangerous.

`feri.config.glob.watch.source` is only useful if you are using Feri in watch mode. If you are, setting this will allow you to choose which files trigger a build from source to dest. https://github.com/ForestMist/feri/blob/master/docs/api/config.md#configglobwatchsource

`feri.config.glob.clean` is useful if you only want to delete certain file extensions from the destination directory. Since Feri can delete your entire destination folder under certain circumstances, I would not recommend trying to use this to protect certain files in your destination folder. https://github.com/ForestMist/feri/blob/master/docs/api/config.md#configglobclean

`feri.config.glob.build` is useful if you want to restrict Feri so it only builds certain file extensions in source and outputs those to dest. https://github.com/ForestMist/feri/blob/master/docs/api/config.md#configglobbuild

**Comment by ForestMist** [comment]
Closing this issue since I like the current rules about where config files can be located.

Netlancer whether Feri ends up being a valid solution for you or not, thanks for trying it. :)
